Repository OWASP/www-project-secure-headers, pull requests merged in 2022-08, with the labels that each got.

#84 Update location info
  .github/ISSUE_TEMPLATE/issue_form.yml
  index.md
Labels: documentation

#87 Add temporary work around for adobe link
  README.md
  tab_compatibility.md
  tab_headers.md
Labels: bug

#86 Bestpractice: mention OSHP Validator
  tab_bestpractices.md
Labels: enhancement

#88 Add references JSON files for headers and others enhancement/fixes
  .github/workflows/headers-generate-json-files.yml
  .gitignore
  .vscode/extensions.json
  README.md
  ci/headers_add.json
  ci/headers_generate_json_files.py
  ci/headers_remove.json
  index.md
  project.code-workspace
  tab_bestpractices.md
Labels: enhancement

#89 Repair broken tables at website html generation time
  ci/headers_add.json
  ci/headers_generate_json_files.py
  ci/headers_remove.json
  tab_bestpractices.md
Labels: bug
